// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Kubernetes Cloud
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/m3/models"
)

// GetStoragePoolsInfoOKCode is the HTTP code returned for type GetStoragePoolsInfoOK
const GetStoragePoolsInfoOKCode int = 200

/*GetStoragePoolsInfoOK A successful response.

swagger:response getStoragePoolsInfoOK
*/
type GetStoragePoolsInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.StoragePoolsInfo `json:"body,omitempty"`
}

// NewGetStoragePoolsInfoOK creates GetStoragePoolsInfoOK with default headers values
func NewGetStoragePoolsInfoOK() *GetStoragePoolsInfoOK {

	return &GetStoragePoolsInfoOK{}
}

// WithPayload adds the payload to the get storage pools info o k response
func (o *GetStoragePoolsInfoOK) WithPayload(payload *models.StoragePoolsInfo) *GetStoragePoolsInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get storage pools info o k response
func (o *GetStoragePoolsInfoOK) SetPayload(payload *models.StoragePoolsInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStoragePoolsInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetStoragePoolsInfoDefault Generic error response.

swagger:response getStoragePoolsInfoDefault
*/
type GetStoragePoolsInfoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetStoragePoolsInfoDefault creates GetStoragePoolsInfoDefault with default headers values
func NewGetStoragePoolsInfoDefault(code int) *GetStoragePoolsInfoDefault {
	if code <= 0 {
		code = 500
	}

	return &GetStoragePoolsInfoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get storage pools info default response
func (o *GetStoragePoolsInfoDefault) WithStatusCode(code int) *GetStoragePoolsInfoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get storage pools info default response
func (o *GetStoragePoolsInfoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get storage pools info default response
func (o *GetStoragePoolsInfoDefault) WithPayload(payload *models.Error) *GetStoragePoolsInfoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get storage pools info default response
func (o *GetStoragePoolsInfoDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStoragePoolsInfoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
